POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Daniel Torres",
  "email": "josedanieltorresgarcia26@gmail.com",
  "password": "umg2025",
  "role": "administrador"
}
